Spotlite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('base/', include('apps.base_spotlite.urls', namespace='base_spotlite')),
    path('auth/', include('apps.auth_spotlite.urls', namespace='auth_spotlite')),
    path('', include('apps.app_spotlite.urls', namespace='app_spotlite')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/app_spotlite/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'app_spotlite'

urlpatterns = [
    path('profile', views.profile, name='profile'),
    path('settings', views.settings, name='settings'),

    path('picture_upload/<str:target>', views.picture_upload, name='picture_upload'),

    path('update_settings', views.update_settings, name='update_settings'),

    path('playlists-editor', views.playlists_editor, name='playlists_editor'),
    path('playlist/<int:playlist_id>/like', views.like_playlist, name='like_playlist'),
    
    path('playlist/<int:playlist_id>/delete', views.delete_playlist, name='delete_playlist'),
    path('playlist/<int:playlist_id>/edit', views.edit_playlist, name='edit_playlist'),
    path('<int:user_id>/playlists', views.user_playlists, name='user_playlists'),
    path('play-history', views.my_history, name='my_history'),
    path('my-<active>', views.my_musics, name='my_musics'),

    path('playlist/<int:playlist_id>/items', views.items_in_playlist, name='items_in_playlist'),
    path('playlist/items/<int:item_id>/delete', views.delete_item_in_playlist, name='delete_item_in_playlist'),

    path('song/<int:song_id>/add-to-playlist', views.add_to_playlist_step1, name='add_to_playlist_step1'),
    path('song/<int:song_id>/add-to-playlist/<int:playlist_id>', views.add_to_playlist_step2, name='add_to_playlist_step2'),
    path('song/<int:song_id>', views.song, name='song'),

    path('album/<int:album_id>/songs', views.song_by_album, name='song_by_album'),
    path('artist/<int:artist_id>/songs', views.song_by_artist, name='song_by_artist'),

    path('song/<int:song_id>/add2history', views.add_song_to_history, name='add_song_to_history'),

    path('songs', views.songs, name='songs'),
    path('song/<int:song_id>/like', views.like_a_song, name='like_a_song'),
    path('song/<int:song_id>/unlike', views.unlike_a_song, name='unlike_a_song'),

    path('presearch/<str:search_keyword>/', views.presearch, name='presearch'),
    path('search/<str:search_keyword>/', views.search, name='search'),
    path('post_search/', views.post_search, name='post_search'),

    path('artist/<int:artist_id>', views.artist, name='artist'),
    path('<int:user_id>/profile', views.profile, name='profile'),   

    path('user/<int:following_id>/follow', views.add_as_friend, name='add_as_friend'),
    path('user/<int:following_id>/unfollow', views.delete_as_friend, name='delete_as_friend'),

    path('change_membership', views.change_membership, name='change_membership'),

    path('', views.index, name='index'),    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/auth_spotlite/urls.py
from django.urls import path
from . import views

app_name = 'auth_spotlite'

urlpatterns = [
    
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('authenticate/<str:action>', views.authenticate, name='authenticate'),
    path('logout', views.logout, name='logout'),
    
    path('', views.index, name='index'),
]

apps/base_spotlite/urls.py
from django.urls import path
from . import views

app_name = 'base_spotlite'

urlpatterns = [
    path('', views.index, name='index'),
]

apps/base_spotlite/models.py
from django.db import models

# Create your models here.

apps/base_spotlite/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'base_spotlite/index.html')

apps/base_spotlite/templates/base_spotlite/about.html
{% extends 'base_spotlite/index.html' %} {% block body %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h1>About</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe similique doloremque aliquam, iste praesentium commodi ea nesciunt omnis modi quam laboriosam sit voluptates odit? Tenetur incidunt facilis laudantium sint repudiandae?</p>
        </div>
    </div>
</div>
{% endblock %}

apps/base_spotlite/templates/base_spotlite/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'base_spotlite/css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'base_spotlite/css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'base_spotlite/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'base_spotlite/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'base_spotlite/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'base_spotlite/css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'base_spotlite/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'base_spotlite/css/spotify.css' %}">
    <title>Spotlite</title>
    <script src="{% static 'base_spotlite/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'base_spotlite/js/amplitude.js' %}"></script>
</head>

<body>
     
    {% include 'base_spotlite/navbar.html' %}
    <div id="content">
        {% block body %}{% endblock %}
    </div>
    {% include 'base_spotlite/player.html' %}
    <script src="{% static 'base_spotlite/js/jquery.history.js' %}"></script>
    <script src="{% static 'base_spotlite/js/popper.min.js' %}"></script>
    <script src="{% static 'base_spotlite/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'base_spotlite/js/spotify.js' %}"></script>
    <script src="{% static 'base_spotlite/js/scripts.js' %}"></script>
    
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>



    <script>
            var playCount = 0;
            Amplitude.init({
            "songs": [

                  {% if song %}

                  {     
                              "name": "{{song.title}}",
                              "artist": "{{song.album.artist.name}}",
                              "album": "{{song.album.title}}",
                              "url": "{{song.mp3url}}",
                              "cover_art_url": "{{song.album.artist.photo}}"
                        },           

            {% for song_ in songs %}

                  {% if song_.id != song.id %}
                        
                        {
                              "name": "{{song_.title}}",
                              "artist": "{{song_.album.artist.name}}",
                              "album": "{{song_.album.title}}",
                              "url": "{{song_.mp3url}}",
                              "cover_art_url": "{{song_.album.artist.photo}}"
                        },
                        
                  {% endif %}
            {% endfor %}

            {% else %}
                  
            {% for song_ in songs %}

                  {% if song_.id != song.id %}
                        
                        {
                              "name": "{{song_.title}}",
                              "artist": "{{song_.album.artist.name}}",
                              "album": "{{song_.album.title}}",
                              "url": "{{song_.mp3url}}",
                              "cover_art_url": "{{song_.album.artist.photo}}"
                        },
                        
                  {% endif %}
            {% endfor %}
             
             {% endif %}      
            ],
            "playlists": {
                  "spotlite": [
                        {% for song in songs %}{{ forloop.counter0 }},{% endfor %}
                  ]
            }
            });
          </script>

</body>

</html>

apps/base_spotlite/templates/base_spotlite/nav.html
<nav class="col-md-2 d-none d-md-block sidebar mt-5">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link active" href="#">
                    <span data-feather="home"></span>
                    Dashboard
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="file"></span>
                    Orders
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="shopping-cart"></span>
                    Products
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="users"></span>
                    Customers
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="bar-chart-2"></span>
                    Reports
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="layers"></span>
                    Integrations
                </a>
            </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Saved reports</span>
            <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="plus-circle"></span>
            </a>
        </h6>
        <ul class="nav flex-column mb-2">
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    Current month
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    Last quarter
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    Social engagement
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    Year-end sale
                </a>
            </li>
        </ul>
    </div>
</nav>

apps/base_spotlite/templates/base_spotlite/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark fixed-top">
    <div class="container-fluid">
        <a class="no-load navbar" href="{% url 'app_spotlite:index' %}">SPOTLITE</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="no-load nav-link my-2 my-sm-0" href="#">About</a>
                </li>
                {% if request.session.user_id %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                        <i class="fa fa-user-circle"></i> {{request.session.firstname}}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="no-load dropdown-item" href="{% url 'app_spotlite:profile' user_id=request.session.user_id %}">Profile</a>
                        <a class="no-load dropdown-item" href="{% url 'app_spotlite:settings' %}">Settings</a>
                        <div class="dropdown-divider"></div>
                        <a class="signout dropdown-item" href="{% url 'auth_spotlite:logout'%}">Sign out</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="btn btn-success my-2 my-sm-0" href="#">
                        <i class="fa fa-user"></i> Join</a>
                </li>
                {% endif %}
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'app_spotlite:post_search' %}" method="POST">
                {% csrf_token %}
                <input class="form-control form-control-sm form-control-dark w-100" type="text" placeholder="Search" aria-label="Search" name="search_keyword">
            </form>
        </div>
    </div>
</nav>

apps/base_spotlite/templates/base_spotlite/player.html
{% load static %}
<footer class="fixed-bottom">
        
        <div id="player" class="current-track pl-5 pr-5">
        
              <div class="current-track__actions">
              
                <a href="#" class="control amplitude-prev" amplitude-playlist="spotlite">
                    <i class="ion-ios-skipbackward"></i>
                </a>

                <a href="#" class="control play button amplitude-play-pause amplitude-paused" amplitude-playlist-main-play-pause="true" amplitude-playlist="spotlite">
                    <i class="ion-ios-play"></i>
                </a>

                <a href="#" class="control play pause btn-play-hidden button amplitude-play-pause amplitude-paused" amplitude-playlist-main-play-pause="true" amplitude-playlist="spotlite">
                    <i class="ion-ios-pause"></i>
                </a>

                <a href="#" class="control amplitude-next" amplitude-playlist="spotlite">
                    <i class="ion-ios-skipforward"></i>
                </a>

                <a href="#" class="control devices amplitude-shuffle" amplitude-playlist="spotlite">
                    <i class="ion-shuffle"></i>
                </a>

                <a href="#" class="control devices amplitude-repeat amplitude-repeat-song" amplitude-playlist="spotlite">
                    <i class="ion-refresh"></i>
                </a>
                
              </div>
              
              <div class="current-track__progress">
              
                <div class="current-track__progress__start">
                    <span class="amplitude-current-time" amplitude-main-current-time="true"></span>
                </div>
                
                <div class="current-track__progress__bar">
                  
                    <input type="range" class="amplitude-song-slider amplitude-song-played-progress" amplitude-playlist-song-slider="true" amplitude-playlist="spotlite"/>
                  
                </div>
                
                <div class="current-track__progress__finish">
                    <span class="amplitude-duration-time" amplitude-main-duration-time="true"></span>
                </div>
                
              </div>
              
              <div class="current-track__options">
              
                <span class="controls">
                  
                  <a href="#" class="control devices">
                    <i class="ion-navicon"></i>
                    <span amplitude-song-info="name" amplitude-playlist="spotlite"></span>
                  </a>
                  
                  <a href="#" class="control volume">
                      
                      <input type="range" class="amplitude-volume-slider"/>
                      
                  </a>
                  
                </span>
                
              </div>
              
            </div>
      </footer>