Spotlite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('base/', include('apps.base_spotlite.urls', namespace='base_spotlite')),
    path('auth/', include('apps.auth_spotlite.urls', namespace='auth_spotlite')),
    path('', include('apps.app_spotlite.urls', namespace='app_spotlite')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/auth_spotlite/urls.py
from django.urls import path
from . import views

app_name = 'auth_spotlite'

urlpatterns = [
    
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('authenticate/<str:action>', views.authenticate, name='authenticate'),
    path('logout', views.logout, name='logout'),
    
    path('', views.index, name='index'),
]

apps/auth_spotlite/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    email = models.CharField(max_length=64, unique=True)
    firstname = models.CharField(max_length=32)
    surname = models.CharField(max_length=32)
    password = models.CharField(max_length=128)
    profilepic = models.CharField(max_length=128)
    premium = models.IntegerField(default=0)
    profilebackground = models.CharField(max_length=128)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/auth_spotlite/views.py
from django.shortcuts import render, redirect
import random, re
from . import models as m
import bcrypt
from django.contrib import messages

EMAIL_REGEX = re.compile(r'^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$')


def index(request):
    imagenr = random.randint(1,8)
    image = '/static/base_spotlite/img/bg{}.jpg'.format(imagenr)
    context = {
        'img_url' : image
    }
    return render(request, 'auth_spotlite/index.html', context)

def register(request):
    imagenr = random.randint(1,8)
    image = '/static/base_spotlite/img/bg{}.jpg'.format(imagenr)
    context = {
        'img_url' : image
    }
    return render(request, 'auth_spotlite/register.html', context)

def login(request):
    return render(request, 'auth_spotlite/login.html')

def authenticate(request, action):
    errors = []
    if action == 'register':
        if request.method == 'POST':
            try: 
                user = m.User.objects.get(email=request.session['html_email'])
                errors.append("There is already an account with the e-mail address.")
                messages.error(request, "There is already an account with the e-mail address.")
                return redirect('auth_spotlite:register')

            except:
                try:
                    email = request.POST['html_email']
                    firstname = request.POST['html_firstname']
                    surname = request.POST['html_surname']
                    password = request.POST['html_password']
                    hashed_password = bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")
                    
                    if len(email) == 0 or len(firstname) == 0 or len(surname) == 0 or len(password) == 0:
                        errors.append("Fields cannot be blank.")
                        messages.error(request, "Fields cannot be blank.")
                    if password != request.POST['html_confirm']:
                        errors.append("Passwords do not match.")
                        messages.error(request, "Passwords do not match.")
                    if len(password) < 6:
                        errors.append("Password must be longer than 6 characters.")
                        messages.error(request, "Password must be longer than 6 characters.")
                    if not EMAIL_REGEX.match(email):
                        errors.append("Invalid e-mail.")
                        messages.error(request, "Invalid e-mail.")

                    if len(errors) == 0:
                        user = m.User() 
                        user.email = email
                        user.firstname = firstname
                        user.surname = surname
                        user.password = hashed_password
                        user.premium = 0
                        user.profilepic = "/static/base_spotlite/img/profile_blank.jpg"
                        user.save()
                        start_session(request, user)
                        return redirect('app_spotlite:index')
                except:
                    raise
                    return redirect('auth_spotlite:register')
        return redirect('auth_spotlite:register')

    elif action == 'login':
        if request.method == 'POST':
            try:
                user = m.User.objects.get(email=request.POST['html_email'])
                password = request.POST['html_password'] 
                if bcrypt.checkpw(password.encode("utf-8"), user.password.encode("utf-8")):
                    start_session(request, user)
                else:
                    errors.append("Password is not correct.")
                    messages.error(request,"Password is not correct.")
                    return redirect('app_spotlite:index')
            except:
                errors.append("User does not exist.")
                messages.error(request,"User does not exist.")
        return redirect('app_spotlite:index')

def logout(request):
    request.session.clear()
    return redirect('auth_spotlite:index')

def start_session(request, user):
    request.session['user_id'] = user.id
    request.session['email'] = user.email
    request.session['firstname'] = user.firstname
    request.session['surname'] = user.surname
    request.session['profilepic'] = user.profilepic
    request.session['premium'] = user.premium

apps/auth_spotlite/templates/auth_spotlite/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="{% static 'base_spotlite/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'base_spotlite/css/styles.css' %}">
    <title>Spotlite</title>
    <style>
        body,
        h1 {
            font-family: "Raleway", sans-serif
        }

        body,
        html {
            height: 100%
        }
        .bgimg {
         
        }
    </style>
</head>

<body>

    {% block body %}
    {% endblock %}


    <script src="{% static 'auth_spotlite/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'auth_spotlite/js/bootstrap.min.js' %}"></script>
</body>

</html>

apps/auth_spotlite/templates/auth_spotlite/errors.html
{% if messages %} 
{% for message in messages %}
<div class="alert alert-danger" role="alert">
    {{message}}
</div>
{% endfor %} {% endif %}

apps/auth_spotlite/templates/auth_spotlite/index.html
{% extends 'auth_spotlite/base.html' %} 
{% load static %}

{% block body %}
{% if 'user_id' in request.session %}
    {% include 'base_spotlite/navbar.html' %}
{% else %}

    {% if 'user_id' in request.session %}
    
    {% else %}
        {% include 'auth_spotlite/login.html' %}
    {% endif %}

{% endif %}


{% endblock %}

apps/auth_spotlite/templates/auth_spotlite/login.html
{% block body %}
<div class="w3-display-container w3-animate-opacity w3-text-white" style="background-image: url('{{img_url}}');
min-height: 100%;background-position: center;background-size: cover;">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 offset-lg-3 col-sm-12 reg-table">
                <form method='POST' action='{% url "auth_spotlite:authenticate" action="login" %}'>
                    {% csrf_token %}
                    <div class="row justify-content-center">
                        <h1>Spotlite</h1>
                    </div>
                    <div class="form-group row">
                        <input type="email" class="form-control col-12" name="html_email" aria-describedby="emailHelp" placeholder="Email">
                    </div>
                    <div class="form-group row">
                        <input type="password" class="form-control col-12" name="html_password" placeholder="Password">
                    </div>
                    <div class="form-group row">
                        <button type="submit" class="btn btn-success col-12">Login</button>
                    </div>
                    <div class="form-group row justify-content-center">
                        <p>Or
                            <a href="{% url 'auth_spotlite:register' %}">register</a> a new account.</p>
                    </div>
                </form>
                {% include 'auth_spotlite/errors.html' %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/auth_spotlite/templates/auth_spotlite/register.html
{% extends 'auth_spotlite/base.html' %} {% block body %}
<div class="w3-display-container w3-animate-opacity w3-text-white" style="background-image: url('{{img_url}}');
min-height: 100%;background-position: center;background-size: cover;">
    <div class="container">
    <div class="row">
        <div class="col-lg-6 offset-lg-3 col-sm-12 reg-table">
            
            <form method='POST' action='{% url "auth_spotlite:authenticate" action="register" %}'>
                {% csrf_token %}
                <div class="row justify-content-center">    
                    <h1>Spotlite</h1>
                </div>
                <div class="form-group row">
                    <input type="email" class="form-control col-12" name="html_email" aria-describedby="emailHelp" placeholder="Enter email">
                </div>
                <div class="form-group row">
                    <input type="text" class="form-control col-12" name="html_firstname" placeholder="First name">
                </div>
                <div class="form-group row">
                    <input type="text" class="form-control col-12" name="html_surname" placeholder="Surname">
                </div>
                <div class="form-group row">
                    <input type="password" class="form-control col-12" name="html_password" placeholder="Password">
                </div>
                <div class="form-group row ">
                    <input type="password" class="form-control col-12" name="html_confirm" placeholder="Confirm password">
                </div>
                <div class="form-group row ">    
                    <button type="submit" class="btn btn-success col-12">Register</button>
                </div>
                <div class="form-group row justify-content-center ">
                    <p>Already have an account? <a href="{% url 'auth_spotlite:index' %}">Sign in.</a></p>
                </div>
            </form>
            {% include 'auth_spotlite/errors.html' %}
        </div>
    </div>
</div>
</div>
    {% endblock %}