Spotlite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('base/', include('apps.base_spotlite.urls', namespace='base_spotlite')),
    path('auth/', include('apps.auth_spotlite.urls', namespace='auth_spotlite')),
    path('', include('apps.app_spotlite.urls', namespace='app_spotlite')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/app_spotlite/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'app_spotlite'

urlpatterns = [
    path('profile', views.profile, name='profile'),
    path('settings', views.settings, name='settings'),

    path('picture_upload/<str:target>', views.picture_upload, name='picture_upload'),

    path('update_settings', views.update_settings, name='update_settings'),

    path('playlists-editor', views.playlists_editor, name='playlists_editor'),
    path('playlist/<int:playlist_id>/like', views.like_playlist, name='like_playlist'),
    
    path('playlist/<int:playlist_id>/delete', views.delete_playlist, name='delete_playlist'),
    path('playlist/<int:playlist_id>/edit', views.edit_playlist, name='edit_playlist'),
    path('<int:user_id>/playlists', views.user_playlists, name='user_playlists'),
    path('play-history', views.my_history, name='my_history'),
    path('my-<active>', views.my_musics, name='my_musics'),

    path('playlist/<int:playlist_id>/items', views.items_in_playlist, name='items_in_playlist'),
    path('playlist/items/<int:item_id>/delete', views.delete_item_in_playlist, name='delete_item_in_playlist'),

    path('song/<int:song_id>/add-to-playlist', views.add_to_playlist_step1, name='add_to_playlist_step1'),
    path('song/<int:song_id>/add-to-playlist/<int:playlist_id>', views.add_to_playlist_step2, name='add_to_playlist_step2'),
    path('song/<int:song_id>', views.song, name='song'),

    path('album/<int:album_id>/songs', views.song_by_album, name='song_by_album'),
    path('artist/<int:artist_id>/songs', views.song_by_artist, name='song_by_artist'),

    path('song/<int:song_id>/add2history', views.add_song_to_history, name='add_song_to_history'),

    path('songs', views.songs, name='songs'),
    path('song/<int:song_id>/like', views.like_a_song, name='like_a_song'),
    path('song/<int:song_id>/unlike', views.unlike_a_song, name='unlike_a_song'),

    path('presearch/<str:search_keyword>/', views.presearch, name='presearch'),
    path('search/<str:search_keyword>/', views.search, name='search'),
    path('post_search/', views.post_search, name='post_search'),

    path('artist/<int:artist_id>', views.artist, name='artist'),
    path('<int:user_id>/profile', views.profile, name='profile'),   

    path('user/<int:following_id>/follow', views.add_as_friend, name='add_as_friend'),
    path('user/<int:following_id>/unfollow', views.delete_as_friend, name='delete_as_friend'),

    path('change_membership', views.change_membership, name='change_membership'),

    path('', views.index, name='index'),    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/app_spotlite/models.py
from django.db import models
from apps.auth_spotlite.models import User

class Follow(models.Model):
   following = models.ForeignKey(User, related_name='following_by', on_delete=models.CASCADE)
   follower = models.ForeignKey(User, related_name='follower_of', on_delete=models.CASCADE)

   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

class Label(models.Model):
   name = models.CharField(max_length=32)
   description = models.TextField()
   logo = models.CharField(max_length=64)

   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

class Artist(models.Model):
   name = models.CharField(max_length=32)
   photo = models.CharField(max_length=128)
   mbid = models.CharField(max_length=64)

   def lastfm_jsonparser(self, data):
      self.name = data['name']
      self.mbid = data['mbid']
      if len(data['image'][3]['#text']) > 0:
         self.photo = data['image'][3]['#text']
      else:
         self.photo = 'http://via.placeholder.com/700x700'

   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

class Album(models.Model):
   title = models.CharField(max_length=32)
   cover = models.CharField(max_length=64)
   mbid = models.CharField(max_length=64)

   artist = models.ForeignKey(Artist, related_name='albums', on_delete=models.CASCADE)

   def lastfm_jsonparser(self, data):
      self.title = data['name']
      self.mbid = data['mbid']
      if len(data['image'][3]['#text']) > 0:
         self.cover = data['image'][3]['#text']
      else:
         self.photo = 'http://via.placeholder.com/700x700'

   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

class Song(models.Model):
   title = models.CharField(max_length=32)
   genre = models.CharField(max_length=32)
   lyric = models.TextField()
   cover = models.CharField(max_length=32)
   mbid = models.CharField(max_length=64)
   mp3url = models.CharField(max_length=128)

   def lastfm_jsonparser(self, data):
      self.title = data['name']
      self.mbid = data['mbid']

   album = models.ForeignKey(Album, related_name='songs', on_delete=models.CASCADE)
   artist = models.ForeignKey(Artist, related_name='songs', on_delete=models.CASCADE) 

   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

class Tag(models.Model):
   name = models.CharField(max_length=32)
   mbid = models.CharField(max_length=64)

   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

class Tagging(models.Model):
   song = models.ForeignKey(Song, related_name='tags', on_delete=models.CASCADE)
   tag = models.ForeignKey(Tag, related_name='songs', on_delete=models.CASCADE)

   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

class Playlist(models.Model):
   title = models.CharField(max_length=32)

   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

class Editor(models.Model):
   user = models.ForeignKey(User, related_name='playlists', on_delete=models.CASCADE)
   playlist = models.ForeignKey(Playlist, related_name='editors', on_delete=models.CASCADE)

   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

class PlaylistItem(models.Model):
   song = models.ForeignKey(Song, related_name='playlist_of', on_delete=models.CASCADE)
   playlist = models.ForeignKey(Playlist, related_name='playlist_items', on_delete=models.CASCADE)
   user = models.ForeignKey(User, related_name='user_playlists_item', on_delete=models.CASCADE)

   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

class History(models.Model):
   user = models.ForeignKey(User, related_name='plays', on_delete=models.CASCADE)
   song = models.ForeignKey(Song, related_name='played_by', on_delete=models.CASCADE)

   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

class Like(models.Model):
   user = models.ForeignKey(User, related_name='likes', on_delete=models.CASCADE)
   song = models.ForeignKey(Song, related_name='like_by', on_delete=models.CASCADE)

   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

apps/app_spotlite/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from . import models as m
from django.db.models import Q
from django.db.models import Count, Sum

from django.conf import settings
from django.core.files.storage import FileSystemStorage
from apps.auth_spotlite import models as um
import random, bcrypt, re

from apps.app_spotlite import lastfm_utilities as lastfm_utils

EMAIL_REGEX = re.compile(r'^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$')

def index(request):
    if 'user_id' in request.session:
        context = {
            'songs': m.Song.objects.all().order_by('-created_at')[:24],
            'albums': m.Album.objects.all().order_by('-created_at')[:24],
            'artists': m.Artist.objects.all().order_by('-created_at')[:24],            
            'histories' : m.History.objects.exclude(user_id=request.session['user_id']).order_by('-created_at')[:8],
            'editors' : m.Editor.objects.filter(user_id=request.session['user_id']).order_by('-created_at'),
            'friends' : m.Follow.objects.filter(follower_id=request.session['user_id']).order_by('-created_at')
        }
        return render(request, 'app_spotlite/index.html', context)
        
    else:
        imagenr = random.randint(1,8)
        image = '/static/base_spotlite/img/bg{}.jpg'.format(imagenr)
        context = {
            'img_url' : image
        }
        return render(request, 'auth_spotlite/index.html', context)


def add_as_friend(request, following_id):
    if 'user_id' in request.session:
        follow = m.Follow()
        follow.follower_id = request.session['user_id']
        follow.following_id = following_id
        follow.save()
        # return redirect(request.META['HTTP_REFERER'])
        return redirect('app_spotlite:profile', following_id)

    return redirect('auth_spotlite:login')

def delete_as_friend(request, following_id):
    if 'user_id' in request.session:
        follow = m.Follow.objects.filter(following_id=following_id)
        follow.delete()
        # return redirect(request.META['HTTP_REFERER'])
        return redirect('app_spotlite:profile', user_id=following_id)
    return redirect('auth_spotlite:login')

def my_history(request):
    if 'user_id' in request.session:
        context = {
            'editors': m.Editor.objects.filter(user_id=request.session['user_id']),
            'histories' : m.History.objects.exclude(user_id=request.session['user_id']).order_by('-created_at')[:8],
            'friends' : m.Follow.objects.filter(follower_id=request.session['user_id']).order_by('-created_at')
        }
        return render(request, 'app_spotlite/play_history.html', context)

    return redirect('auth_spotlite:login')

def my_musics(request, active):
    if 'user_id' in request.session:
        context = {
            'active': active,
            'albums': m.Album.objects.all()[:24],
            'artists': m.Artist.objects.all()[:24],      
            'editors': m.Editor.objects.filter(user_id=request.session['user_id']),
            'likes' : m.Like.objects.filter(user_id=request.session['user_id']).order_by('-created_at'),
            'histories' : m.History.objects.exclude(user_id=request.session['user_id']).order_by('-created_at')[:8],
            'friends' : m.Follow.objects.filter(follower_id=request.session['user_id']).order_by('-created_at')
        }
        return render(request, 'app_spotlite/my_musics.html', context)
    
    return redirect('auth_spotlite:login')



def songs(request):
    context = {
        'songs' : m.Song.objects.all().order_by('-updated_at'),
        'histories' : m.History.objects.exclude(user_id=request.session['user_id']).order_by('-created_at')[:8],
        'friends' : m.Follow.objects.filter(follower_id=request.session['user_id']).order_by('-created_at')
    }
    return render(request, 'app_spotlite/songs.html', context)


def song(request, song_id):
    like = False
    like_check = m.Like.objects.filter(song_id=song_id, user_id=request.session['user_id'])
    if len(like_check) > 0:
        like = True

    context = {
        'albums': m.Album.objects.all()[:5],
        'artists': m.Artist.objects.all()[:5],
        'related_artist': m.Song.objects.filter(tags__song_id=song_id).distinct().values('artist_id'),
        'artists_grid': m.Artist.objects.all()[:12],
        'song' : m.Song.objects.get(id=song_id),
        'editors': m.Editor.objects.filter(user_id=request.session['user_id']),
        'songs': m.Song.objects.annotate(total=Count('played_by')).order_by('-total')[:10], #POPULAR SONGS
        'like': like,
        'histories' : m.History.objects.exclude(user_id=request.session['user_id']).order_by('-created_at')[:8],
        'friends' : m.Follow.objects.filter(follower_id=request.session['user_id']).order_by('-created_at')
    }
    return render(request, 'app_spotlite/song.html', context)


def song_by_album(request, album_id):
    if 'user_id' in request.session:
        context = {
            'songs': m.Song.objects.filter(album_id=album_id)[:24],
            'album': m.Album.objects.get(id=album_id),          
            'histories' : m.History.objects.exclude(user_id=request.session['user_id']).order_by('-created_at')[:8],
            'editors' : m.Editor.objects.filter(user_id=request.session['user_id']),
            'friends' : m.Follow.objects.filter(follower_id=request.session['user_id']).order_by('-created_at')
        }
        return render(request, 'app_spotlite/songs_by_album.html', context)

    return redirect('auth_spotlite:login')


def song_by_artist(request, artist_id):
    if 'user_id' in request.session:
        context = {
            'songs': m.Song.objects.filter(artist_id=artist_id)[:24],
            'artist': m.Artist.objects.get(id=artist_id),          
            'histories' : m.History.objects.exclude(user_id=request.session['user_id']).order_by('-created_at')[:8],
            'editors' : m.Editor.objects.filter(user_id=request.session['user_id']),
            'friends' : m.Follow.objects.filter(follower_id=request.session['user_id']).order_by('-created_at')
        }
        return render(request, 'app_spotlite/songs_by_artist.html', context)

    return redirect('auth_spotlite:login')



def like_a_song(request, song_id):
    if 'user_id' in request.session:
        check = m.Like.objects.filter(user_id=request.session['user_id'], song_id=song_id)
        if len(check) == 0:
            like = m.Like()
            like.user_id = request.session['user_id']
            like.song_id = song_id
            like.save()

        return redirect('app_spotlite:index')

    return redirect('app_spotlite:profile')


def unlike_a_song(request, song_id):
    if 'user_id' in request.session:
        like = m.Like.objects.get(user_id=request.session['user_id'], song_id=song_id)
        like.delete()

        return redirect('app_spotlite:my_musics')

    return redirect('app_spotlite:profile')

def add_song_to_history(request, song_id):
    if 'user_id' in request.session:

        history = m.History()
        history.user_id = request.session['user_id']
        history.song_id = song_id
        
        check = m.History.objects.filter(user_id=request.session['user_id']).order_by('-created_at')[:1]

        if len(check) > 0:
            if check[0].song_id != song_id:
                history.save()
        else:
            history.save()

        # return redirect(request.META['HTTP_REFERER'])
        return redirect('app_spotlite:song', song_id=song_id)
    
    return redirect('auth_spotlite:login')


def add_to_playlist_step1(request, song_id):
    if 'user_id' in request.session:
        context = {
            'editors': m.Editor.objects.filter(user_id=request.session['user_id']),
            'song_id': song_id,
            'histories' : m.History.objects.exclude(user_id=request.session['user_id']).order_by('-created_at')[:8],
            'friends' : m.Follow.objects.filter(follower_id=request.session['user_id']).order_by('-created_at')
        }
        return render(request, 'app_spotlite/playlists.html', context)

    return redirect('auth_spotlite:login')


def add_to_playlist_step2(request, song_id, playlist_id):
    if 'user_id' in request.session:
        if len(m.PlaylistItem.objects.filter(user_id=request.session['user_id'], song_id=song_id, playlist_id=playlist_id)) == 0:
            playlist_item = m.PlaylistItem()
            playlist_item.song_id = song_id
            playlist_item.playlist_id = playlist_id
            playlist_item.user_id = request.session['user_id']
            playlist_item.save()
        
        return redirect('app_spotlite:items_in_playlist', playlist_id=playlist_id)

    return redirect('auth_spotlite:login')


def playlists_editor(request):
    if 'user_id' in request.session:
        if request.method == 'POST':
            try:
                playlist = m.Playlist()
                playlist.title = request.POST['html_title']
                playlist.save()

                #save to editor
                editor = m.Editor()
                editor.playlist_id = playlist.id
                editor.user_id = request.session['user_id']
                editor.save()

                return redirect(request.META['HTTP_REFERER'])
            except:
                messages.error(request, 'invalid input')

        context = {
            'editors': m.Editor.objects.filter(user_id=request.session['user_id']),
            'user_editors': m.Editor.objects.filter(user_id=request.session['user_id']),
            'can_add': True,
            'user': False,
            'histories' : m.History.objects.exclude(user_id=request.session['user_id']).order_by('-created_at')[:8],
            'friends' : m.Follow.objects.filter(follower_id=request.session['user_id']).order_by('-created_at')
        }
        return render(request, 'app_spotlite/playlists.html', context = context)

apps/app_spotlite/templates/app_spotlite/content_right.html
<div class="content__right">
    <section class="playlist">
  
        <span class="no-load">
  
          Friend Activities
  
        </span>
  
      </section>
        {% for history in histories %}
        <section class="playing">

          <div class="playing__art">
    
            <img src="{{ history.user.profilepic }}" alt="Album Art">
    
          </div>
    
          <div class="playing__song">
    
            <a href="{% url 'app_spotlite:song' song_id=history.song_id %}" class="playing__song__name" style="font-size:11px">{{ history.user.firstname }} playing {{ history.song.title }}</a>
    
          </div>
    
        </section>
        {% endfor %}

    <div class="overview__related">

        <section class="playlist">
  
            <span class="no-load">
      
              My Friends
      
            </span>
      
          </section>
            
            <div class="related-artists">

                {% for friend in friends %}
            
              <a href="{% url 'app_spotlite:profile' user_id=friend.following.id %}" class="related-artist">
              
                <span class="related-artist__img">
                
                  <img src="{{ friend.following.profilepic }}" alt="Hoodie Allen">
                  
                </span>
                
                <span class="related-artist__name">{{ friend.following.firstname }} {{ friend.following.surname }}</span>
                
              </a>

              {% endfor %}
              
            </div>

          </div>
</div>

apps/app_spotlite/templates/app_spotlite/index.html
{% extends "base_spotlite/index.html" %} {% block body %}
<section class="content" style="margin-top: 60px; height: 100%">

      {% include 'app_spotlite/content_left.html' %}

      <div class="content__middle">
            <div class="artist is-verified">
            <div class="artist__header" style="height: auto;">
                  <div class="artist__navigation" style="height: 60px;">
                  <ul class="nav nav-tabs" role="tablist">
                        <li role="artists">
                        <a href="#artists" aria-controls="artists" role="tab" data-toggle="tab">Artists</a>
                        </li>
                        <li role="presentation" class="activeBAK">
                        <a href="#songs" aria-controls="songs" role="tab" data-toggle="tab">Song</a>
                        </li>
                        <li role="albums">
                        <a href="#albums" aria-controls="albums" role="tab" data-toggle="tab">Albums</a>
                        </li>
                  </ul>
                  </div>

            </div>
            <div class="artist__content">
                  <div class="tab-content">
        
                      <!-- Artist Search Result -->
                      <div role="tabpanel" class="tab-pane active" id="artists">
                            <div class="media-cards">
                                  {% for artist in artists %}
                                  <div class="media-card">
                                  <div class="media-card__image" style="background-image: url({{artist.photo}});">
                                        <i class="ion-ios-play"></i>
                                  </div>
                                  <a href="{% url 'app_spotlite:song_by_artist' artist_id=artist.id %}" class="media-card__footer" href="{% url 'app_spotlite:artist' artist_id=artist.id %}" style="color: white; text-align: center">{{ artist.name }}</a>
                                  </div>
                                  {% empty %}
                                  <p style="color: white">No artist found</p>
                                  {% endfor %}
                            </div>
                      </div>
                    <!-- Song Search Result -->
                    <div role="tabpanel" class="tab-pane" id="songs">
                            <div class="album__tracks">

                                    <div class="tracks">
                                            <div class="tracks__heading">
                                            <div class="tracks__heading__number">#</div>
                                            <div class="tracks__heading__added"></div>
                                            <div class="tracks__heading__title">Title</div>
                                            <div class="tracks__heading__length">
                                                  <i class="ion-ios-stopwatch-outline"></i>
                                            </div>
                                            <div class="tracks__heading__popularity">
                                                  <!-- <i class="ion-thumbsup"></i> -->
                                            </div>
                                            </div>
                                            {% for song in songs %}
                                            <div class="track">
                                            <div class="track__number">{{ forloop.counter }}</div>
                                            <div class="track__added">
                                                  <div class="dropdown">
                                                  <a class="btn btn-link ion-plus not-added" href="#" role="button" id="dropdown_not_added" data-toggle="dropdown" aria-haspopup="true"
                                                        aria-expanded="false">
                                                  </a>
                                                  <div class="dropdown-menu" aria-labelledby="dropdown_not_added">
                                                        {% for editor in editors %}
                                                        <a class="dropdown-item add2playlist" href="#" data-href="{% url 'app_spotlite:add_to_playlist_step2' song_id=song.id playlist_id=editor.playlist_id %}">{{ editor.playlist.title }}</a>
                                                        {% endfor %}
                                                        <div class="dropdown-divider"></div>
                                                        <a class="no-load dropdown-item" href="{% url 'app_spotlite:playlists_editor' %}">Create playlist</a>
                                                  </div>
                                                  </div>
                                            </div>
                                            <div class="track__title" style="position: relative;"><a class="no-load" href="{% url 'app_spotlite:song' song_id=song.id %}">{{song.title}}</a></div>
                                          
                                            <div class="track__length">1:11 &nbsp; &nbsp; </div>
                                    
                                            </div>
                                            {% endfor %}
                                        </div>

                            </div>
                    </div>

                        <!-- Album Search Result -->
                        <div role="tabpanel" class="tab-pane" id="albums">
                                <div class="media-cards">
                                {% for album in albums %}
                                <div class="media-card">
                                      <div class="media-card__image" style="background-image: url({{album.cover}});">
                                      <i class="ion-ios-play"></i>
                                      </div>
                                      <a href="{% url 'app_spotlite:song_by_album' album_id=album.id %}" class="media-card__footer" style="color: white; text-align: center">{{ album.title }}</a>
                                </div>
                                      {% empty %}
                                      <p style="color: white">No album found</p>
                                {% endfor %}
                                </div>
                          </div>
                    
                  </div>
            </div>
            </div>
      </div>

      {% include 'app_spotlite/content_right.html' %}

</section>

<script>
        $('.add2playlist').click(function(){
              url = $(this).attr('data-href');
              $.get(url, function( data ) {
                    alert('successfull add to this playlist');
              });
        });      
  </script>


{% endblock %}

apps/app_spotlite/templates/app_spotlite/playlist-edit.html
{% extends 'base_spotlite/index.html' %} {% block body %}

<p>&nbsp;</p><p>&nbsp;</p>
<div class="container mt-5 text-white">

    <div class="row">
        <h2 class="mb-4">Edit Playlist</h2>
            <div class="row form-control ml-1">
                <form action="{% url 'app_spotlite:edit_playlist' playlist_id=playlist.id %}" method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  <input type="hidden" name="destination" value="{{ destination }}" />
                  <div class="form-group">
                      <label for="name">Title</label>
                      <input type="text" class="form-control" name="html_title" value="{{ playlist.title }}" id="name" placeholder="Title">
                  </div>
                  <button type="submit" class="btn btn-primary">Update</button>
              </form>                
            </div>                    
    </div>
</div>
{% endblock %}

apps/app_spotlite/templates/app_spotlite/playlists.html
{% extends "base_spotlite/index.html" %} {% block body %}
<section class="content" style="margin-top: 60px; height: 100%">

      {% include 'app_spotlite/content_left.html' %}

      <div class="content__middle pl-5 pt-5 text-white">

                {% if can_add %}
                <div class="row">
                    <h2 class="mb-4">Add Playlist:</h2>
            
                    <div class="form-control border-success" style="max-width: 90%;">
                        <form action="{% url 'app_spotlite:playlists_editor' %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="name">Title</label>
                                <input type="text" class="form-control" name="html_title" id="name" placeholder="Title">
                            </div>
                            <button type="submit" class="btn btn-primary">Add</button>
                        </form>            
                    </div>
                </div>
                <p>&nbsp;</p>
                <p>&nbsp;</p>
            
                {% endif %}
            
                <div class="row">
                    <div class="col-xs-12">   
                        {% if can_add %}
                        {% elif user %}
                            <h1>{{user.firstname}}'s Playlists</h1>
                        {% else %}
                            <h1>Playlists</h1>
                        {% endif %}
                        <p>&nbsp;</p>
            
                        <table class="data-table table table-striped table-bordered col-12" width="100%">
                            <thead>
                                <tr>
                                    <th style="width: 500px;">Title</th>
                                    <th width="300">Created</th>
                                    <th width="140">Action</th>
                                </tr>
                            </thead>
                            <tbody>                    
            
                                {% for editor in user_editors %}
                                <tr>
                                    <td>
                                            {% if song_id %}
                                                <a href="{% url 'app_spotlite:add_to_playlist_step2' song_id=song_id playlist_id=editor.playlist_id %}"><h5 class="card-title">{{ editor.playlist.title }}</h5></a>
                                            {% else %}
                                                <a href="{% url 'app_spotlite:items_in_playlist' playlist_id=editor.playlist_id %}"><h5 class="card-title">{{ editor.playlist.title }}</h5></a>
                                            {% endif %}                                     
                                    </td>
                                    <td>{{ editor.playlist.created_at }}</td>
                                    <td>
                                            {% if user %}
                                            <a href="{% url 'app_spotlite:like_playlist' playlist_id=editor.playlist_id %}">like it</a>
            
                                            {% else %}
                                            <a href="{% url 'app_spotlite:edit_playlist' playlist_id=editor.playlist_id %}">edit</a>
                                            | 
                                            <a href="{% url 'app_spotlite:delete_playlist' playlist_id=editor.playlist_id %}">delete</a>                            
                                            {% endif %}                                    
                                    </td>
                                </tr>
                                {% endfor %}
            
                            </tbody>
                        </table>
                    </div>
                </div>
        

                      </div>

      {% include 'app_spotlite/content_right.html' %}

</section>
{% endblock %}